"""CLAUDE.md management for agent-container sections."""

from __future__ import annotations

import logging
import re
from pathlib import Path

from ..config import AgentConfig

logger = logging.getLogger(__name__)


def setup_claude_md(config: AgentConfig, workdir: str) -> None:
    """Generate and inject an agent-container section into CLAUDE.md.

    Uses HTML comment tags to delimit the managed section so it can be
    updated or removed without touching user content.
    """
    claude_dir = Path(workdir) / ".claude"
    claude_md = claude_dir / "CLAUDE.md"

    existing = ""
    if claude_md.exists():
        existing = claude_md.read_text()

    agent_id = config.name
    role = config.env.get("CLAUDE_AGENT_ROLE", config.labels.get("role", ""))
    agent_env_id = config.env.get("CLAUDE_AGENT_ID", config.name)

    lines = [
        f'<!-- agent-container:start id="{agent_id}" -->',
        f"## Agent: {agent_id} (auto-generated by scitex-agent-container)",
        "",
    ]

    if config.skills.required:
        lines.append("### Required Skills")
        lines.append("Load these skills at startup:")
        lines.append("```skills")
        for skill in config.skills.required:
            lines.append(skill)
        lines.append("```")
        lines.append("")

    if config.skills.available:
        lines.append("### Available Skills")
        lines.append("These skills can be used when needed:")
        lines.append("```skills")
        for skill in config.skills.available:
            lines.append(skill)
        lines.append("```")
        lines.append("")

    lines.append("### Agent Role")
    if role:
        lines.append(f"- Role: {role}")
    lines.append(f"- ID: {agent_env_id}")
    lines.append(f'<!-- agent-container:end id="{agent_id}" -->')

    section = "\n".join(lines)

    pattern = (
        rf'<!-- agent-container:start id="{re.escape(agent_id)}" -->.*?'
        rf'<!-- agent-container:end id="{re.escape(agent_id)}" -->'
    )
    if re.search(pattern, existing, re.DOTALL):
        updated = re.sub(pattern, section, existing, flags=re.DOTALL)
    else:
        separator = (
            "\n\n"
            if existing and not existing.endswith("\n\n")
            else ("\n" if existing and not existing.endswith("\n") else "")
        )
        updated = existing + separator + section + "\n"

    claude_dir.mkdir(parents=True, exist_ok=True)
    claude_md.write_text(updated)
    logger.info("CLAUDE.md updated for agent %s at %s", agent_id, claude_md)


def cleanup_claude_md(config: AgentConfig, workdir: str) -> None:
    """Remove the agent-container section from CLAUDE.md."""
    claude_md = Path(workdir) / ".claude" / "CLAUDE.md"
    if not claude_md.exists():
        return

    existing = claude_md.read_text()
    agent_id = config.name

    pattern = (
        rf'\n*<!-- agent-container:start id="{re.escape(agent_id)}" -->.*?'
        rf'<!-- agent-container:end id="{re.escape(agent_id)}" -->\n?'
    )
    updated = re.sub(pattern, "", existing, flags=re.DOTALL)

    if updated != existing:
        claude_md.write_text(updated)
        logger.info("CLAUDE.md cleaned up for agent %s at %s", agent_id, claude_md)
