"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-agent-container' references
in its source tree. Two outcomes:

- Module installed AND import succeeds → test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` → `scitex_io._loading._load_cache`) →
  test FAILS loudly.
- Module NOT installed (peer standalone absent in the CI env) →
  test is SKIPPED via `pytest.importorskip`. The umbrella's CI
  (which installs every peer) catches cross-package renames.
"""

import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    "scitex_cards",
    "scitex_cards._throughput",
    "scitex_config",
    "scitex_config._ecosystem",
    "scitex_container",
    "scitex_dev",
    "scitex_dev._cli._completion",
    "scitex_dev._cli.ecosystem",
    "scitex_dev.hooks",
    "scitex_dev.hosts",
    "scitex_dev.jobs",
    "scitex_dev.linter._rules._base",
    "scitex_dev.linter._rules._lookup",
    "scitex_dev.linter.checker",
    "scitex_dev.store",
    "scitex_dev.system_deps",
    "scitex_dev.versioning",
    "scitex_cards",
    "scitex_logging",
    "scitex_notification",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import_resolves_to_real_module(module_name):
    """Importing scitex-agent-container's declared cross-package dependency must succeed.

    SKIP ON THE ROOT, HARD-IMPORT THE FULL PATH (PS-140 §2). These are two
    different questions and `importorskip(full_path)` collapses them into one:

        pytest.importorskip("scitex_dev.linter._rules._lookup")

    skips when ANY segment is missing — including the LEAF. So the exact
    failure this file exists to catch, an internal rename like
    ``_lookup`` -> ``_lookups``, is reported as a SKIP and the suite stays
    green. The test could not fail for the reason it was written.

    The distinction that has to be preserved:

        peer package absent   -> legitimately SKIP (lean install, optional
                                 extra, marker-gated dependency; the umbrella
                                 CI installs every peer and catches renames)
        peer present, path gone -> must FAIL LOUDLY (that is a real break)

    Hence: `importorskip` on the ROOT only, then a hard `import_module` of the
    full dotted path. Do NOT "simplify" this to a bare hard import — that
    breaks every lean install where the peer is legitimately not there.

    Worked example: scitex-ai/scitex-hpc#88.

    NOTE FOR REGENERATION: this file is written by
    ``scitex-dev ecosystem write-integration-tests``. This function sits
    BELOW the END sentinel, which the header declares hand-editable, so a
    regeneration should preserve it. If a future regeneration does clobber
    this body, the fix belongs in the generator rather than here — otherwise
    PS-140 re-fires on every leaf that regenerates.
    """
    # Arrange
    name = module_name
    root = name.split(".")[0]
    # Act
    pytest.importorskip(root)
    mod = importlib.import_module(name)
    # Assert
    assert mod is not None
