"""Cross-package import gate (PS-140) for scitex-agent-container.

Every module listed here is imported by this package's source but
OWNED by a peer standalone. A rename or move on the other side of
that boundary is invisible to this package's unit tests and
surfaces as ModuleNotFoundError in a user's process — which is how
the `scitex_io._load_cache` rename went undetected for weeks.

Generated by `scitex-dev ecosystem install-cross-package-gate`.
Regenerate with:

    scitex-dev ecosystem install-cross-package-gate scitex-agent-container --force

Do not hand-edit the list: the PS-140 auditor recomputes it from
source on every run and fails on any drift in either direction
(a missing entry OR a stale one).
"""

import importlib

import pytest

CROSS_PACKAGE_IMPORTS = [
    'scitex_cards',
    'scitex_cards._throughput',
    'scitex_config',
    'scitex_config._ecosystem',
    'scitex_container',
    'scitex_dev',
    'scitex_dev._cli._completion',
    'scitex_dev._cli.ecosystem',
    'scitex_dev.hooks',
    'scitex_dev.hosts',
    'scitex_dev.jobs',
    'scitex_dev.linter._rules._base',
    'scitex_dev.linter._rules._lookup',
    'scitex_dev.linter.checker',
    'scitex_dev.system_deps',
    'scitex_dev.versioning',
    'scitex_logging',
    'scitex_notification',
    'scitex_todo',
]


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import_resolves(module_name):
    # Arrange / Act — a real import, not importlib.util.find_spec:
    # find_spec only proves a module is FINDABLE on the path, and
    # the failures this gate exists to catch (a renamed symbol
    # re-exported through a package __init__) happen at EXECUTION.
    module = importlib.import_module(module_name)

    # Assert
    assert module is not None
