"""Cross-package import gate (PS-140) for scitex-agent-container.

Every module listed here is imported by this package's source but
OWNED by a peer standalone. A rename or move on the other side of
that boundary is invisible to this package's unit tests and
surfaces as ModuleNotFoundError in a user's process — which is how
the `scitex_io._load_cache` rename went undetected for weeks.

Generated by `scitex-dev ecosystem install-cross-package-gate`.

generated-by: scitex-dev 0.56.5

A GATE NOBODY CAN DATE IS A CLAIM ABOUT AN UNKNOWN PAST. This
list is a snapshot of the cross-package imports as they stood
when the stamp above was written; it does not update itself, and
a stale copy looks exactly like a current one. Measured
2026-08-16: 17 gates across the fleet carried NO stamp and named
a generator that never existed as a command -- the real writer
was a one-shot script since deleted -- so the only way to tell a
fossil from a live gate was a filesystem sweep of mtimes. The
same disease had already been found in the audit gate (68 of 70
still calling audit_all_for_package() with no path=), and the
same cure applies: say which version wrote you.

Regenerate with:

    scitex-dev ecosystem install-cross-package-gate scitex-agent-container --force

Do not hand-edit the list: the PS-140 auditor recomputes it from
source on every run and fails on any drift in either direction
(a missing entry OR a stale one).

Hand-written cases go BELOW the second sentinel. Everything there
is preserved byte-identically across regeneration; everything
between the sentinels is overwritten.
"""

import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    'scitex_cards',
    'scitex_cards._mirror_rows',
    'scitex_cards._throughput',
    'scitex_config',
    'scitex_config._ecosystem',
    'scitex_container',
    'scitex_dev',
    'scitex_dev._cli._completion',
    'scitex_dev._cli.ecosystem',
    'scitex_dev.hooks',
    'scitex_dev.hosts',
    'scitex_dev.jobs',
    'scitex_dev.linter._rules._base',
    'scitex_dev.linter._rules._lookup',
    'scitex_dev.linter.checker',
    'scitex_dev.store',
    'scitex_dev.store._store',
    'scitex_dev.system_deps',
    'scitex_dev.versioning',
    'scitex_logging',
    'scitex_notification',
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import_resolves_to_real_module(module_name):
    """Importing scitex-agent-container's declared cross-package dependency must succeed.

    PS-140 §2. Skip on the ROOT distribution, then HARD-IMPORT the full path.

    ``pytest.importorskip("scitex_dev.hooks")`` skips when ANY part of the
    dotted path is missing, so a peer that IS installed but has renamed or
    removed a submodule reports SKIPPED -- which is exactly the case the
    module docstring above promises will "FAIL loudly". The two-step form is
    what makes that promise true: an absent peer still skips (a lean install
    is legitimate), while a present peer that lost the submodule now fails.

    This is not hypothetical. On 2026-08-17 ``scitex_dev.hooks`` gained a
    required ``HookRule`` field; the consumer-side break was invisible on
    every developer machine because this test, and the plugin test beside it,
    both SKIPPED rather than failed. CI -- which installs the peer -- failed,
    and develop went red for every PR with no local run able to reproduce it.
    A skip is not a pass.
    """
    # Arrange
    root = module_name.split(".")[0]
    pytest.importorskip(root)
    # Act
    mod = importlib.import_module(module_name)
    # Assert
    assert mod is not None
