"""Renderer for the GENERATED peer client config (``sac host push-config``).

Master-SSOT peer topology (ADR-0021): the master's own
``~/.scitex/agent-container/config.yaml`` is the fleet's ONLY hand-edited
topology file. Every other host runs a GENERATED minimal client config,
pushed one-way master → peer by ``sac host push-config``. This module is
the pure renderer for that file — no ssh, no file I/O, and no clock read
unless the caller declines to inject ``now``.

Why text, not ``yaml.dump``
---------------------------
The file is compared BYTE-WISE against what sits on the peer (that is
how drift detection stays honest), so the renderer must be deterministic
down to header comments and key order. ``yaml.dump`` guarantees neither
across library versions; a template guarantees both. A ``yaml.safe_load``
self-check still asserts the emitted text parses back to exactly the
mapping we meant — a renderer that can emit unparseable or misquoted
YAML must raise, never return.

What is deliberately NOT emitted
--------------------------------
``via:`` chains, ``env_preamble``, glob templates, and every peer other
than the master. Verified against the peer-side readers: a client host
needs its own canonical name (pins its state.db identity),
``comms_nodes.sync_on_start: false`` (ADR-0020's startup-hang guard),
and its route BACK to the master — nothing else. Anything more would be
topology duplicated across N hosts, which is the drift machine this
subsystem exists to retire.
"""

from __future__ import annotations

from datetime import datetime, timezone

import yaml

from .._state.host_config import Config

__all__ = [
    "GENERATED_HEADER_MARK",
    "embedded_master_sha",
    "is_generated",
    "render_peer_config",
    "strip_generated_stamp",
]

# The stable prefix of every generated config's FIRST line. The master's
# name follows on the same line (it is a renderer parameter), so the
# whole first line cannot be one constant — the invariant prefix is the
# contract that :func:`is_generated`, the push-config verdicts, and the
# ``sac host add/set/remove`` guard all key on.
GENERATED_HEADER_MARK = "# GENERATED by"

# The one VOLATILE line: it records when a push landed, so it always
# differs between a peer's copy and a fresh render. Comparisons strip it
# (see :func:`strip_generated_stamp`); the master-config sha embedded on
# the same line is still compared via :func:`embedded_master_sha`.
_GENERATED_STAMP_PREFIX = "# generated: "


def is_generated(text: str) -> bool:
    """True when ``text`` is a sac-generated client config.

    The contract is the FIRST line: every rendered config starts with
    :data:`GENERATED_HEADER_MARK` and names the generating verb. An
    empty file, or any file whose first line differs, is NOT generated —
    callers treat that as hand-edited, because a stripped or reworded
    header on a real config file is exactly the drift this exists to
    catch.
    """
    first_line = text.split("\n", 1)[0]
    return first_line.startswith(GENERATED_HEADER_MARK) and (
        "(sac host push-config)" in first_line
    )


def strip_generated_stamp(text: str) -> str:
    """``text`` minus its ``# generated:`` line (the only volatile line).

    The push timestamp records WHEN a file landed; two configs that
    differ only there carry the same topology, and the drift verdicts
    must not cry wolf over provenance. Everything else — including the
    embedded master-config sha — still participates in comparison.
    """
    return "".join(
        line
        for line in text.splitlines(keepends=True)
        if not line.startswith(_GENERATED_STAMP_PREFIX)
    )


def embedded_master_sha(text: str) -> str:
    """The ``sha256:<12>`` recorded on the ``# generated:`` line, or ``""``."""
    for line in text.splitlines():
        if line.startswith(_GENERATED_STAMP_PREFIX) and "sha256:" in line:
            return line.rsplit("sha256:", 1)[1].strip()
    return ""


def render_peer_config(
    peer_name: str,
    cfg: Config,
    *,
    master_name: str = "ywata-note-win",
    now: datetime | None = None,
    master_sha: str = "",
) -> str:
    """Render ``peer_name``'s generated client config as YAML text.

    Deterministic: the same inputs yield the same bytes (pass ``now`` to
    pin the provenance stamp; omitting it reads the UTC clock). The
    peer's route back to the master comes from the peer's
    ``reverse_ssh`` in the MASTER's config, falling back to
    ``master_name`` itself when unset (i.e. the peer's ``~/.ssh/config``
    is expected to resolve it — the ADR-0020 step-6 shape).

    Args:
        peer_name: the client host this config is FOR (pins its
            ``host.canonical``, and therefore its state.db identity).
        cfg: the MASTER's loaded config (the SSOT being projected).
        master_name: the master's canonical host name.
        now: provenance timestamp; ``None`` = ``datetime.now(utc)``.
        master_sha: sha256 hexdigest of the master config bytes; the
            first 12 chars are stamped into the header (``"unknown"``
            when empty).

    Raises:
        ValueError: when the rendered text does not parse back to the
            intended mapping (a name that would need YAML quoting).
    """
    spec = cfg.peers.get(peer_name)
    reverse_ssh = (spec.reverse_ssh if spec is not None else "") or master_name
    stamp = (now if now is not None else datetime.now(timezone.utc)).isoformat()
    sha12 = master_sha[:12] or "unknown"
    text = (
        f"{GENERATED_HEADER_MARK} {master_name} "
        "(sac host push-config) — DO NOT HAND-EDIT.\n"
        "# A hand edit here is DRIFT: `sac host push-config --check` will shout,\n"
        "# and the next push will REFUSE to overwrite until run with --adopt.\n"
        "# Edit the MASTER's config.yaml instead; a push regenerates this file.\n"
        f"# source: {master_name}:~/.scitex/agent-container/config.yaml\n"
        f"{_GENERATED_STAMP_PREFIX}{stamp} from master-config sha256:{sha12}\n"
        "host:\n"
        f"  canonical: {peer_name}\n"
        "comms_nodes:\n"
        "  sync_on_start: false\n"
        "peers:\n"
        f"  {master_name}:\n"
        f"    ssh: {reverse_ssh}\n"
    )
    _assert_roundtrip(text, peer_name, master_name, reverse_ssh)
    return text


def _assert_roundtrip(
    text: str, peer_name: str, master_name: str, reverse_ssh: str
) -> None:
    """Fail loudly if the rendered text does not parse to what we meant.

    Text templating cannot quote; this check makes misquoting impossible
    to SHIP rather than merely unlikely. A renderer error here is a
    master-config problem (a name YAML cannot take as a plain scalar),
    and the operator should hear about it at render time — not as a
    corrupted client config discovered on a peer later.
    """
    expected = {
        "host": {"canonical": peer_name},
        "comms_nodes": {"sync_on_start": False},
        "peers": {master_name: {"ssh": reverse_ssh}},
    }
    try:
        parsed = yaml.safe_load(text)
    except yaml.YAMLError as exc:
        raise ValueError(
            f"rendered client config for '{peer_name}' is not parseable YAML "
            f"({exc}) — a name in it needs quoting this renderer does not do"
        ) from exc
    if parsed != expected:
        raise ValueError(
            f"rendered client config for '{peer_name}' parses to {parsed!r}, "
            f"not the intended mapping {expected!r} — a name in it needs "
            "quoting this renderer does not do"
        )
