"""Tests for the generated client-config renderer (ADR-0021).

PA-306: no ``unittest.mock`` — real :class:`Config` objects loaded from
real tmp files. The golden-string test is deliberately byte-exact: the
push-config verdicts compare BYTES, so the renderer's output format IS
its contract. Each test: AAA markers (TQ002), one assertion (TQ007),
behaviour-shaped 3+-word name (TQ003).
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import pytest
import yaml

from scitex_agent_container._hostsync._peer_config import (
    GENERATED_HEADER_MARK,
    embedded_master_sha,
    is_generated,
    render_peer_config,
    strip_generated_stamp,
)
from scitex_agent_container._state.host_config import load as load_cfg

_NOW = datetime(2026, 7, 16, 8, 0, 0, tzinfo=timezone.utc)
_SHA = "aabbccddeeff0011223344556677889900aabbccddeeff001122334455667788"

_GOLDEN = (
    "# GENERATED by ywata-note-win (sac host push-config) — DO NOT HAND-EDIT.\n"
    "# A hand edit here is DRIFT: `sac host push-config --check` will shout,\n"
    "# and the next push will REFUSE to overwrite until run with --adopt.\n"
    "# Edit the MASTER's config.yaml instead; a push regenerates this file.\n"
    "# source: ywata-note-win:~/.scitex/agent-container/config.yaml\n"
    "# generated: 2026-07-16T08:00:00+00:00 from master-config sha256:aabbccddeeff\n"
    "host:\n"
    "  canonical: spartan\n"
    "comms_nodes:\n"
    "  sync_on_start: false\n"
    "# listen.token_file — the STABLE, canonical-name-keyed bearer path\n"
    "# `sac host push-config --rotate-tokens` writes (ADR-0021 §Tokens).\n"
    "# NOT YET READ AT BOOT: `sac listen` resolves its token from\n"
    "# --token-file, else tokens/listen-<gethostname()>.token. Until this\n"
    "# host's launcher passes --token-file <the path below>, this key\n"
    "# records WHERE the rotated bearer is, not what the listen reads.\n"
    "listen:\n"
    "  token_file: ~/.scitex/agent-container/tokens/listen-spartan.token\n"
    "peers:\n"
    "  ywata-note-win:\n"
    "    ssh: ywata-note-win\n"
)


@pytest.fixture
def master_cfg(tmp_path: Path):
    """A real master config with one plain peer (no reverse_ssh)."""
    p = tmp_path / "config.yaml"
    p.write_text("peers:\n  spartan:\n    ssh: spartan\n")
    return load_cfg(p)


# ---------------------------------------------------------------------------
# render_peer_config
# ---------------------------------------------------------------------------


def test_render_matches_the_golden_string_exactly(master_cfg):
    # Arrange
    # (master_cfg holds one plain peer; all render inputs are pinned)
    # Act
    text = render_peer_config(
        "spartan",
        master_cfg,
        master_name="ywata-note-win",
        now=_NOW,
        master_sha=_SHA,
    )
    # Assert — byte-exact: the drift verdicts compare bytes.
    assert text == _GOLDEN


def test_render_is_deterministic_for_same_inputs(master_cfg):
    # Arrange
    # (identical inputs on both calls)
    # Act
    first = render_peer_config("spartan", master_cfg, now=_NOW, master_sha=_SHA)
    second = render_peer_config("spartan", master_cfg, now=_NOW, master_sha=_SHA)
    # Assert
    assert first == second


def test_reverse_ssh_defaults_to_master_name(master_cfg):
    # Arrange
    # (the spartan peer entry carries no reverse_ssh)
    # Act
    text = render_peer_config("spartan", master_cfg, master_name="master-x", now=_NOW)
    # Assert — the route back falls back to the master's own name.
    assert "    ssh: master-x\n" in text


def test_explicit_reverse_ssh_lands_in_the_route_back(tmp_path: Path):
    # Arrange — reverse_ssh set on the peer in the MASTER's config.
    p = tmp_path / "config.yaml"
    p.write_text(
        "peers:\n"
        "  nas:\n"
        "    ssh: admin@192.168.11.22\n"
        "    reverse_ssh: ywatanabe@10.0.0.5\n"
    )
    cfg = load_cfg(p)
    # Act
    text = render_peer_config("nas", cfg, master_name="master-x", now=_NOW)
    # Assert
    assert "    ssh: ywatanabe@10.0.0.5\n" in text


def test_render_emits_the_peer_as_canonical_host(master_cfg):
    # Arrange
    # (the emitted YAML must PARSE back to the intended values)
    # Act
    text = render_peer_config("spartan", master_cfg, now=_NOW, master_sha=_SHA)
    # Assert
    assert yaml.safe_load(text)["host"]["canonical"] == "spartan"


def test_render_pins_sync_on_start_false(master_cfg):
    # Arrange
    # (ADR-0020's startup-hang guard must always be pinned)
    # Act
    text = render_peer_config("spartan", master_cfg, now=_NOW, master_sha=_SHA)
    # Assert
    assert yaml.safe_load(text)["comms_nodes"]["sync_on_start"] is False


def test_render_never_emits_via_chains(tmp_path: Path):
    # Arrange — the master routes to bm198 via a hop; the CLIENT config
    # must not replicate that topology.
    p = tmp_path / "config.yaml"
    p.write_text("peers:\n  mba: {ssh: m}\n  bm198:\n    ssh: bm198\n    via: [mba]\n")
    cfg = load_cfg(p)
    # Act
    text = render_peer_config("bm198", cfg, now=_NOW, master_sha=_SHA)
    # Assert
    assert "via" not in text


def test_render_never_emits_env_preamble(tmp_path: Path):
    # Arrange
    p = tmp_path / "config.yaml"
    p.write_text(
        "peers:\n"
        "  spartan:\n"
        "    ssh: spartan\n"
        "    env_preamble:\n"
        "      - source /usr/share/lmod/lmod/init/bash\n"
    )
    cfg = load_cfg(p)
    # Act
    text = render_peer_config("spartan", cfg, now=_NOW, master_sha=_SHA)
    # Assert
    assert "env_preamble" not in text


def test_render_raises_on_a_name_yaml_cannot_take_plain(master_cfg):
    # Arrange — a peer name that would need quoting must FAIL LOUDLY at
    # render time, never ship as a corrupted client config.
    bad_peer_name = "bad: name"
    # Act
    # Assert — the raise IS the assertion.
    with pytest.raises(ValueError):
        render_peer_config(bad_peer_name, master_cfg, now=_NOW, master_sha=_SHA)


def test_render_stamp_defaults_to_unknown_without_master_sha(master_cfg):
    # Arrange
    # (empty master_sha must still render honestly)
    # Act
    text = render_peer_config("spartan", master_cfg, now=_NOW)
    # Assert
    assert "sha256:unknown" in text


# ---------------------------------------------------------------------------
# is_generated / header helpers
# ---------------------------------------------------------------------------


def test_is_generated_true_for_rendered_output(master_cfg):
    # Arrange
    text = render_peer_config("spartan", master_cfg, now=_NOW, master_sha=_SHA)
    # Act
    verdict = is_generated(text)
    # Assert
    assert verdict


def test_is_generated_false_for_hand_written_text():
    # Arrange
    hand = "host:\n  aliases: {}\npeers:\n  mba: {ssh: m}\n"
    # Act
    verdict = is_generated(hand)
    # Assert
    assert not verdict


def test_is_generated_false_for_empty_text():
    # Arrange
    empty = ""
    # Act
    verdict = is_generated(empty)
    # Assert
    assert not verdict


def test_golden_first_line_starts_with_the_header_mark():
    # Arrange — the mark is the contract every consumer (verdicts, CRUD
    # guard) keys on.
    first_line = _GOLDEN.split("\n", 1)[0]
    # Act
    starts = first_line.startswith(GENERATED_HEADER_MARK)
    # Assert
    assert starts


def test_strip_generated_stamp_removes_only_the_stamp_line():
    # Arrange
    # (the golden config carries exactly one '# generated:' line)
    # Act
    stripped = strip_generated_stamp(_GOLDEN)
    # Assert — the volatile line is gone.
    assert "# generated:" not in stripped


def test_strip_generated_stamp_keeps_every_other_line():
    # Arrange
    expected = _GOLDEN.replace(
        "# generated: 2026-07-16T08:00:00+00:00 "
        "from master-config sha256:aabbccddeeff\n",
        "",
    )
    # Act
    stripped = strip_generated_stamp(_GOLDEN)
    # Assert — nothing else went with it.
    assert stripped == expected


def test_embedded_master_sha_reads_the_stamped_sha12():
    # Arrange
    # (the golden config stamps sha256:aabbccddeeff)
    # Act
    sha12 = embedded_master_sha(_GOLDEN)
    # Assert
    assert sha12 == "aabbccddeeff"


def test_embedded_master_sha_empty_for_hand_text():
    # Arrange
    hand = "peers: {}\n"
    # Act
    sha12 = embedded_master_sha(hand)
    # Assert
    assert sha12 == ""
